---
- name: Plays for Ubuntu
  hosts: target

  tasks:
    - name: Install FTP Server (vsftpd) - Ubuntu
      apt:
        name: vsftpd
        state: present
      when: ansible_distribution == "Ubuntu"


    - name: Install FTP Server (vsftpd) - CentOS
      yum:
        name: vsftpd
        state: present
      when: ansible_distribution == "CentOS"


- name: Install ftp client
  hosts: target
  remote_user: vagrant
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: latest lftp version installed
    yum:
      name: lftp
      state: latest
